version: '2.1'
executors:
  al2_container:
    docker:
      - image: 'amazonlinux:2'
    working_directory: '/app/'

commands:
  install_awscli2:
    steps:
      - run:
          name: 'import public key'
          command: |
            cat \<<EOF > aws.pub
            -----BEGIN PGP PUBLIC KEY BLOCK-----

            mQINBF2Cr7UBEADJZHcgusOJl7ENSyumXh85z0TRV0xJorM2B/JL0kHOyigQluUG
            ZMLhENaG0bYatdrKP+3H91lvK050pXwnO/R7fB/FSTouki4ciIx5OuLlnJZIxSzx
            PqGl0mkxImLNbGWoi6Lto0LYxqHN2iQtzlwTVmq9733zd3XfcXrZ3+LblHAgEt5G
            TfNxEKJ8soPLyWmwDH6HWCnjZ/aIQRBTIQ05uVeEoYxSh6wOai7ss/KveoSNBbYz
            gbdzoqI2Y8cgH2nbfgp3DSasaLZEdCSsIsK1u05CinE7k2qZ7KgKAUIcT/cR/grk
            C6VwsnDU0OUCideXcQ8WeHutqvgZH1JgKDbznoIzeQHJD238GEu+eKhRHcz8/jeG
            94zkcgJOz3KbZGYMiTh277Fvj9zzvZsbMBCedV1BTg3TqgvdX4bdkhf5cH+7NtWO
            lrFj6UwAsGukBTAOxC0l/dnSmZhJ7Z1KmEWilro/gOrjtOxqRQutlIqG22TaqoPG
            fYVN+en3Zwbt97kcgZDwqbuykNt64oZWc4XKCa3mprEGC3IbJTBFqglXmZ7l9ywG
            EEUJYOlb2XrSuPWml39beWdKM8kzr1OjnlOm6+lpTRCBfo0wa9F8YZRhHPAkwKkX
            XDeOGpWRj4ohOx0d2GWkyV5xyN14p2tQOCdOODmz80yUTgRpPVQUtOEhXQARAQAB
            tCFBV1MgQ0xJIFRlYW0gPGF3cy1jbGlAYW1hem9uLmNvbT6JAlQEEwEIAD4WIQT7
            Xbd/1cEYuAURraimMQrMRnJHXAUCXYKvtQIbAwUJB4TOAAULCQgHAgYVCgkICwIE
            FgIDAQIeAQIXgAAKCRCmMQrMRnJHXJIXEAChLUIkg80uPUkGjE3jejvQSA1aWuAM
            yzy6fdpdlRUz6M6nmsUhOExjVIvibEJpzK5mhuSZ4lb0vJ2ZUPgCv4zs2nBd7BGJ
            MxKiWgBReGvTdqZ0SzyYH4PYCJSE732x/Fw9hfnh1dMTXNcrQXzwOmmFNNegG0Ox
            au+VnpcR5Kz3smiTrIwZbRudo1ijhCYPQ7t5CMp9kjC6bObvy1hSIg2xNbMAN/Do
            ikebAl36uA6Y/Uczjj3GxZW4ZWeFirMidKbtqvUz2y0UFszobjiBSqZZHCreC34B
            hw9bFNpuWC/0SrXgohdsc6vK50pDGdV5kM2qo9tMQ/izsAwTh/d/GzZv8H4lV9eO
            tEis+EpR497PaxKKh9tJf0N6Q1YLRHof5xePZtOIlS3gfvsH5hXA3HJ9yIxb8T0H
            QYmVr3aIUes20i6meI3fuV36VFupwfrTKaL7VXnsrK2fq5cRvyJLNzXucg0WAjPF
            RrAGLzY7nP1xeg1a0aeP+pdsqjqlPJom8OCWc1+6DWbg0jsC74WoesAqgBItODMB
            rsal1y/q+bPzpsnWjzHV8+1/EtZmSc8ZUGSJOPkfC7hObnfkl18h+1QtKTjZme4d
            H17gsBJr+opwJw/Zio2LMjQBOqlm3K1A4zFTh7wBC7He6KPQea1p2XAMgtvATtNe
            YLZATHZKTJyiqA==
            =vYOk
            -----END PGP PUBLIC KEY BLOCK-----
            EOF
            gpg --import aws.pub
      - run:
          name: 'download sigunature'
          command: 'curl -o awscliv2.sig https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip.sig'
      - restore_cache:
          name: 'Restore awscli2'
          key: 'awscli2-{{ checksum `awscliv2.sig` }}'
      - run:
          name: 'download awscli2'
          command: 'test -e awscliv2.zip || curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"'
      - run:
          name: 'verify binary'
          command: 'gpg --verify awscliv2.sig awscliv2.zip'
      - run:
          name: 'unzip && install awscli2'
          command: 'unzip awscliv2.zip && ./aws/install'
      - save_cache:
          name: 'Cache awscli2'
          key: 'awscli2-{{ checksum `awscliv2.sig` }}'
          paths:
            - 'awscliv2.zip'

jobs:
  build:
    executor: 'al2_container'
    steps:
      - checkout
      - run:
          name: 'install requirements'
          command: 'yum install -y zip unzip tar gzip groff-base'
      - install_awscli2
      - run:
          name: 'create revision file'
          command: 'echo ${CIRCLE_SHA1:0:8} > application/REVISION'
      - run:
          name: 'files for deploy'
          command: '(cd application ; zip -r source.zip codedeploy appspec.yml Dockerfile REVISION)'
      - run:
          name: 'deploy'
          command: 'aws s3 cp application/source.zip s3://${S3_BUCKET_NAME}/'

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: 'master'
